services:
  server:
    build: .
    container_name: aibot
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      DB_URI: mongodb://root:admin@mongo:27017/
      DB_NAME: aibot
      API_KEY: 
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./db_data/:/data/db/
